name: auto_adap
channels:
  - conda-forge
dependencies:
  - pip=24.2
  - python=3.11.9
  - pip:
      - torch
      - torchvision
      - transformers
      - accelerate
      - scikit-learn
      - gdown
      - tqdm
